<a href="https://colab.research.google.com/github/LAKSH3002/Python_Libraries_Studies/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy cheatsheet
# 1) Array creation
np.array([]) - creation of array
np.array(()) - creation of array from a tuple
np.arange(startlimit, endlimit, interval) - creating a sequence of integers
np.zeros() - creating an array of zeros
np.ones() - creating an array of ones
np.linspace() - to print any n number of values between a, b including the first and last values
np.random.random((3, 4)) - creation of array with dimensions
np.random.randint(-10, 10, 6) - creation of array with different numbers

# 2) Array features
arr.ndim() - Gives the dimension of the array
arr.size - Gives the size of the array
arr.shape - Gives the shape of the array
arr.dtype - Gives the data type of the array
newarr = arr.astype(datatype) - to convert array from one data type to another

# 3) Array Slicing
array_name[start:end:step(optional)] - while slicing, the ending index will not be considered.
For 2-d, 3-d, 4-d, we have to provide range in start and end of slicing of the array.

# 4) Array Indexing
array_name[index] - for 1d array
array_name[index1, index2] - for 2d array and so on.

# 5) Array copy and view
copyarr = arr.copy() - copy owns the og data, any changes made in copy does not affect original array and vice versa.
viewarr = arr.view() - view does not own the data, any changes made affects the original array and vice vera.
copyarr.base & viewarr.base - Checking if array owns its data

# 6) Iteration of the array
Use for loops and while loops (but it has limitations, it wont work well for longer arrays)
nditer solves the issue of too many iterations and prints each item by occupying less space.
nditer is accessible using the object.

We can Iterate array with different data types.
step 1: pass op_dtypes argument, declare it with the expected data type.
step 2: add buffer, this is a space where change in data type occurs.
In order to enable nditer, we declare flags = buffer.

# 7) Other functions
arr.reshape() - reshapes the array
In order to convert multidimensional array into 1D array, flatten it: reshape(-1)
np.intersect1d(arr1, arr2) - Intersection of arrays
np.union1d(arr1, arr2) - Union of arrays
np.setdiff1d(arr1,arr2) - Difference of arrays

# 8) Joins in an array
In numpy we join arrays using axes
It is a horizontal join if the axes is set to 0, axis 1 is applicable only if array is above or equal to 2 dimensions.

np.concatenate((arr1, arr2)) - joins the two arrays, giving an axes is optional
np.stack((arr1,arr2)) - joins the two arrays
rowstack = np.hstack((arr1,arr2)) prints the join in a single row
colstack = np.vstack((arr1,arr2,arr3)) - prints the join one above the other (columns)
depthstack = np.dstack((j1,j2)) - stacking using depth.

# 9) Splitting of array : reverse operation of joining
split = np.array_split(array,number_of_splits)
we have split() method too, but it wont adjust itself when elements are less in source array.

For splitting a 2d array, its the same process, except if you want to customize
split = np.array_split(array, number_of_splits, axis=1)

# An alternative to this approach is to use hsplit(): Horizontal split (similiar to hstack), its going to give similiar result.
# similar to vstack and dstack are vsplit() and dsplit()

x = np.where(array_name == 90) - returns index position of the specified value (can give an expression as well)
ss = np.searchsorted(array_name,value, side='right') - used to find out where can we insert a specific number in array(works on sorted arrays)
np.sort(array_name) - sorts the array

In [ ]:
# **Numpy Syntax, meanings and use cases.**

# Learned about the following functions, its use cases, its exceptions and more.

# arr.ndim(), arr.size, arr.shape, arr.dtype, arrcopy(), arr.view(), arr.reshape(), arr.astype()
# nditer(), ndenumerate(), concatenate(), flattern(), stack(), hstack(), vstack(), dstack()
# array_split(), hsplit(), vsplit(), dsplit()
# .where(), .searchsorted(),
# iteration of arrays using for and while loops.

# More functions:
# Intersection, difference, union of arrays
# np.intersect1d(arr1, arr2), np.union1d(arr1, arr2), np.setdiff1d(arr1,arr2), np.setxor1d(arr1, arr2)

# np: instance of numpy libaray
# np.array( [item1, item2...] ): To create an array and store it under a variable.
# You can create 1-d, 2-d, 3-d and n-d array, declare it properly with the brackets.
# There are many more ways to create an array: np.zeros(), np.arrange(start value, end value, interval), np.linspace()
# To find dimensions of an array use: array_name.ndim()
# Indexing of array: array_name[index] for 1-d, array_name[index1, index2] for 2-d and so on.

# 1) Slicing of array:

# array_name[start:end:step(optional)], while slicing, the ending index will not be considered while slicing it.
# For 2-d, 3-d, 4-d, we have to provide range in start and end of slicing of the array.

# 2) Data types of the array:

# You can specify the data type while declaring the array. To convert into another data type: use arr.astype('data type')

# 3) Copy and view of the array

# copy owns the og data, any changes made in copy does not affect original array and vice versa. Declaration: copyarr = arr.copy()
# view does not own the data, any changes made affects the original array and vice vera. Declaration: viewarr = arr.view()

# 4) Reshaping of Array

# It is done using the reshape() function. You have to provide proper dimensions based on the type of the array.
# In case you want to flatten the array just add -1 inside the bracket.

# 5) Iteration of the array

# Use for loops and while loops (but it has limitations, it wont work well for longer arrays)
# nditer solves the issue of too many iterations and prints each item by occupying less space.
# nditer is accessible using the object.

# We can Iterate array with different data types.
# step 1: pass op_dtypes argument, declare it with the expected data type.
# step 2: add buffer, this is a space where change in data type occurs.
# In order to enable nditer, we declare flags = buffer.

# ndenumerate(): It gets you the index of the element along with the element.

# 6) Joining of array

# In order to join the array: you can use either concatenate() or stack()
# In the above two functions you can provide axis.
# In concatenate if you use axis as 0 it will be a horizontal join, axis 1 and above is only applicable for multi dimensional array
# We can stack horizontally, vertically and in depth using hstack(), vstack() and dstack()
# When we provide axis as 1 in stack() function it then executes as a stack function.

# 7) Splitting of an array

# Splitting of array : reverse operation of joining
# we use array_split() for splitting arrays, The return value is a list.
# we have split() method too, but it wont adjust itself when elements are less in source array.
# While splitting provide arr name and number of splits.
# For splitting a 2d array, its the same process, except if you want to customize
# lets say we want to split the array into 3 parts, with 1st element of each 1d array in each splitted array, use axis=1
# An alternative to this approach is to use hsplit(): Horizontal split (similiar to hstack), its going to give similiar result.
# similar to vstack and dstack are vsplit() and dsplit()

# 8) Search

# You search for a value using .where() function
# You find out where you can insert a value in an array using searchsorted() function
# To sort an array, you can use .sort() method.

# 9) Filtering of arrays

# Filtering of arrays
# In Numpy, you filter an array using a boolean index list.
# Create a filter array that will return only even elements from the original array:
# Instead of iterating, we can also filter directly from the array

In [ ]:
# Numpy
# It has all functions to work with linear algebra and matrices.
# np acts as an object/alias for the library.
import numpy as np

# Simple array declaration and printing using array() function
x = np.array([1,3,4,5,6])
print(x)
print(np.__version__)

# array from tuples. It can also be extracted from sets, dictionaires as well.
x2 = np.array((10,12,14,16))
print(x2)

# Creation of n dimensions array using random values
e = np.random.random((3, 4))
f = np.random.randint(-10, 10, 6)
print("ARRAY WITH RANDOM VALUES ARE \n", e)
print()
print("ARRAY WITH RANDOM INTEGER VALUES ARE \n", f)
# return type will be Float

# creating a sequence of integers
# from 0 to 30 with a step of 7
f = np.arange(0, 30, 7)
print("\n The sequential array is\n", f)
# The arrange function will begin with a specified limit and end to a specified limit and will print all the values, if not given any intervals.

# linspace - to print any n number of values between a, b including the first and last values
# where a is initial limit and b is the final limit
g = np.linspace(1, 8, 5)
print("\n sequential array with 10 values between 0 and 8 are\n", g)

# dimensions of array
d1 = np.array(34) # 0-D
d2 = np.array([1,2,3,4,5,6,7,8,9]) # 1-D
d3 = np.array([[2,3,4], [5,6,7]]) # 2-D
d4 = np.array([[[1,2,3],[2,2,2]],[[2,1,2], [3,2,2]]]) # 3-D

# to get dimenison of the array
print(d1.ndim)
print(d4.ndim)

# There can be more than 3 dimeniosna as well, in that explicitly mention the dimensions while declaring the array

# Indexing of array
print(d2[4]) # 1-d
print(d3[1,2]) # 2-d
print(d4[0,1,2]) # 3-d

# Slicing of array for 1-d array
# array[start:end:step]
print(d2[-3:-1])
print(d2[1:4:2])
print(d2[::2]) # start to end with a step of 2

# 2-D slicing
print(d3[0:2,1:3]) # [2,3] [6,7] # doubt (solve)
print(d3[1, 1:4]) # From the second bracket, slice index 1 to 4.
print(d3[0:2, 2]) # From both the brackets, return column number 2 element

# Numpy has some different data types
# i: integer, u:unsigned integer, f: float, c: complex float, s: string
dt1 = np.array([1,2,3], dtype='i4')
print(dt1)
print(dt1.dtype)

dt2 = np.array(['s','k','m'], dtype='S')
print(dt2)
print(dt2.dtype)

# in case different data types are mentioned in the array, an error will be displayed.

# Changing data type of the array: This will change float to int data type
xx = np.array([1.1,2.2,3.5])
newarray = xx.astype('i')
print(newarray)

# conversion of string array to boolean array using astype()
yz = np.array(['s','k','m'])
new = yz.astype(bool)
print(new)

[1 3 4 5 6]
2.0.2
[10 12 14 16]
ARRAY WITH RANDOM VALUES ARE 
 [[0.83288199 0.16335097 0.61059068 0.27144863]
 [0.22558865 0.76441387 0.4383385  0.85414766]
 [0.43444364 0.80788063 0.17677858 0.16989075]]

ARRAY WITH RANDOM INTEGER VALUES ARE 
 [-5  8 -7 -5 -5 -1]

 The sequential array is
 [ 0  7 14 21 28]

 sequential array with 10 values between 0 and 8 are
 [1.   2.75 4.5  6.25 8.  ]
0
3
5
7
2
[7 8]
[2 4]
[1 3 5 7 9]
[[3 4]
 [6 7]]
[6 7]
[4 7]
[1 2 3]
int32
[b's' b'k' b'm']
|S1
[1 2 3]
[ True  True  True]


In [ ]:
# Till now declaration, indexing, slicing and data types done
# Now next few topics

# Copy and view of the array.
# copy of the array owns the data, any changes made in the copy will not original array and vice versa.
# In view, the changes made will affect the original array and vice versa

# copy of array
a1 = np.array([1,3,5,6])
copyarray = a1.copy()
copyarray[1] = 33

print(a1)
print(copyarray)
print()

# view of array
a2 = np.array([1,3,6,8])
viewarray = a2.view()
viewarray[0] = 5

print(a2)
print(viewarray)
print()

# checking if array owns its data
print(copyarray.base)
print(viewarray.base)

# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
ad = np.array([1,2,3,4], ndmin = 5)
print('shape of array', ad.shape) # doubt (solve)

[1 3 5 6]
[ 1 33  5  6]

[5 3 6 8]
[5 3 6 8]

None
[5 3 6 8]
shape of array (1, 1, 1, 1, 4)


In [ ]:
# Reshaping of array.
# Done using reshape function
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = x.reshape([5,2])
d2 = np.array([[1,2,3], [4,5,6]])
print(y)
z = x.reshape([1,2,5])
print(z)
print(y.base) # returns original array, thus its a view.

# Unknown dimesion: Like give an unknow value, python will automatically make it into 3D
w = x.reshape([1,2,-1])
print(w)

# In order to convert multidimensional array into 1D array, flatten it: reshape(-1)
# There are many more functions: they are in advanced part of numpy.

# Iteration of array
for x in d2:
  print(x) # prints each row one by one

# To print each element use nested loops. For 2D and 3D as well
# Since we cant always nest the loop based on array size.

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2 = np.array([1, 2, 3])

# nditer solves the issue of too many iterations and prints each item by occupying less space.
# nditer is accessible using the object
for x in np.nditer(arr):
  print(x)

# Iterating array with different data types.
# step 1: pass op_dtypes argument, declare it with the expected data type.
# step 2: add buffer, this is a space where change in data type occurs.
# In order to enable nditer, we declare flags = buffer.
for x in np.nditer(arr2, flags=['buffered'], op_dtypes=['S']):
  print(x)

# ndenumerate(): It gets you the index of the element along with the element.
for idx, x in np.ndenumerate(arr2):
  print(idx, x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
[ 1  2  3  4  5  6  7  8  9 10]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
[1 2 3]
[4 5 6]
1
2
3
4
5
6
7
8
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
(0,) 1
(1,) 2
(2,) 3


In [ ]:
# Joins in an array: In numpy we join arrays using axes
j1 =  np.array([1,2,3])
j2 = np.array([10,12,14])
jarr = np.array([9,3,5])
# It is a horizontal join if the axes is set to 0
j3 = np.concatenate((j1,j2))
print(j3)
# axis 1 is applicable only if array is above or equal to 2 dimensions.

# joining using stack functions
j4 = np.stack((j1,j2)) # if axis=0, then it works like vstack
print(j4)

# Stacking along rows, columns and height
# prints the join in a single row
rowstack = np.hstack((j1,j2))
# prints the join one above the other (columns)
colstack = np.vstack((j1,j2,jarr))
print(rowstack)
print(colstack)
# Stacking using depth
depthstack = np.dstack((j1,j2))
print(depthstack)

# question: Can I join 1d array with n-d arrays using axis 1.
# What is dstack exactly, need more explanation.

[ 1  2  3 10 12 14]
[[ 1  2  3]
 [10 12 14]]
[ 1  2  3 10 12 14]
[[ 1  2  3]
 [10 12 14]
 [ 9  3  5]]
[[[ 1 10]
  [ 2 12]
  [ 3 14]]]


In [ ]:
# Splitting of array : reverse operation of joining
# we use array_split() for splitting arrays, The return value is a list.
# we have split() method too, but it wont adjust itself when elements are less in source array.
sp1 = np.array([10,90,120,550,470,380])
sp2 = np.array_split(sp1,2)
print(sp2)
sp3 = np.array_split(sp1,4)
print(sp3)

# For splitting a 2d array, its the same process, except if you want to customize
# lets say we want to split the array into 3 parts, with 1st element of each 1d array in each splitted array, use axis=1
split4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
split5 = np.array_split(split4, 3, axis=1)
print(split5)

# An alternative to this approach is to use hsplit(): Horizontal split (similiar to hstack), its going to give similiar result.
# similar to vstack and dstack are vsplit() and dsplit()

x = np.where(sp1 == 90)
print(x) # returns index position.

# Find the indexes where the values are even:
y = np.where(sp1%2 == 1)
print(y)

# searchsorted() function: used to find out where can we insert a specific number in the array
# It works on sorted arrays, Example:
ss = np.searchsorted(sp1,120, side='right')
print(ss)

sort1 = np.array([97,21,33,11,5,2])
print(np.sort(sort1))
sort2d = np.array([[4,1,3],[9,2,5]])
print(np.sort(sort2d))

# You can also sort strings, booleans, float values as well.

[array([ 10,  90, 120]), array([550, 470, 380])]
[array([10, 90]), array([120, 550]), array([470]), array([380])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
(array([1]),)
(array([], dtype=int64),)
3
[ 2  5 11 21 33 97]
[[1 3 4]
 [2 5 9]]


In [ ]:
# Filtering of arrays
# In Numpy, you filter an array using a boolean index list.
Farr = np.array([1,4,3,7,5,9,8])
# Create a filter array that will return only even elements from the original array:
fil_arr = []

for x in Farr:
  if x%2==0:
    fil_arr.append(True)
  else:
    fil_arr.append(False)

newarr = Farr[fil_arr]
print(newarr)

# Instead of iterating, we can also filter directly from the array
filter_array = Farr > 5
new_arr = Farr[filter_array]
print(new_arr)

[4 8]
[7 9 8]
